name: Test all

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    env:
      DOWNLOAD_TOKEN: ${{ secrets.DOWNLOAD_TOKEN}}
      API_URL: ${{ secrets.API_URL }}
    steps:
      - uses: actions/checkout@v4
      - name: Cache turbo build setup
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - uses: pnpm/action-setup@v4
        with:
          version: 9.0.0
      - run: echo "node_version=$(cat .github/nodejs.version)" >> $GITHUB_ENV
      - name: "Use node ${{ env.node_version }}"
        uses: actions/setup-node@v3
        with:
          node-version: "${{ env.node_version }}"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Format & Lint
        run: pnpm format
      - name: Test
        run: pnpm test
